### ISSUE TITLE
JS SDK checklist

### ISSUE THREAD

**Issue by ghost** [GovLab/ogrx-2#60]
(by wed)

- [x] sdk based paper list (all papers)
- [x] paper list pagination
- [x] sdk based individual paper view
- [x] hook up links (to papers) on paper list
- [x] add useSDK option for selected readings list page
- [x] sdk based selected reading individual page
- [x] loading icon
- [x] clean up ui

(by wed if possible)

- [x] filter / search on paper list (at least enough to activate filtering links on paper list)
- [x] hook up filtering links
- [x] markdown support for selected readings

(next sprint)

- [ ] add useSDK option for organization list page
- [ ] sdk based organization page
- [x] category pages
- [ ] fully reimplement filtering / searching features

(future)

- [ ] async element loading
- [ ] URL mapping for old links (big issue)
- [ ] turn off old build method for papers and remove migration shims (eg useSDK flags)

**Comment by ghost** [comment]
https://github.com/evilstreak/markdown-js/releases
